services:
    web:
      build: ./web
      ports:
        - "3000:3000"
      volumes:
        - type: bind
          source: ./web
          target: /app
      depends_on:
        - api
      command:
        tail -f /dev/null
  
    api:
      build: ./api
      ports:
        - "8080:8080"
      volumes:
        - type: bind
          source: ./api
          target: /app
      depends_on:
        - db
      command:
        tail -f /dev/null
  
    db:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: quizchronos
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      volumes:
        - ./db/data:/var/lib/mysql
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - "3306:3306"
