services:
    web:
      build: ./web
      volumes:
        - ./web/src:/app
          - ./web/src/node_modules:/app/node_modules
        - ./web/src/src/routes:/app/src/routes
        - ./web/src/src/lib:/app/src/lib
      ports:
        - 5173:5173
      depends_on:
        - api
  
    api:
      build: ./api
      ports:
        - "8080:8080"
      volumes:
        - type: bind
          source: ./api/src
          target: /app
      depends_on:
        - db
      command:
        ./main
  
    db:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: quizchronos
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      volumes:
        - ./db/data:/var/lib/mysql
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - "3306:3306"

volumes:
  node_modules: